// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRecruitment.API.Data;

#nullable disable

namespace SmartRecruitment.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806104738_AddJobSeekerModule")]
    partial class AddJobSeekerModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.CvMetadata", b =>
                {
                    b.Property<int>("CvMetadataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CvMetadataId"));

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("JobSeekerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CvMetadataId");

                    b.HasIndex("JobSeekerProfileId")
                        .IsUnique();

                    b.ToTable("CvMetadata", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Education", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<int>("JobSeekerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EducationId");

                    b.HasIndex("JobSeekerProfileId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.EmployerProfile", b =>
                {
                    b.Property<int>("EmployerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployerProfileId"));

                    b.Property<string>("CompanyDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("EmployerProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmployerProfile");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Experience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperienceId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrentJob")
                        .HasColumnType("bit");

                    b.Property<int>("JobSeekerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExperienceId");

                    b.HasIndex("JobSeekerProfileId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.JobSeekerProfile", b =>
                {
                    b.Property<int>("JobSeekerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobSeekerProfileId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("JobSeekerProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserId1")
                        .IsUnique()
                        .HasFilter("[UserId1] IS NOT NULL");

                    b.ToTable("JobSeekerProfiles", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.JobSeekerSkill", b =>
                {
                    b.Property<int>("JobSeekerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("JobSeekerProfileId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSeekerSkills", null, t =>
                        {
                            t.HasCheckConstraint("CK_JobSeekerSkills_ProficiencyLevel", "[ProficiencyLevel] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_JobSeekerSkills_YearsOfExperience", "[YearsOfExperience] >= 0");
                        });
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Vacancy", b =>
                {
                    b.Property<int>("VacancyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VacancyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EducationRequirement")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EmployerProfileId")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RequiredExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VacancyId");

                    b.HasIndex("EmployerProfileId");

                    b.ToTable("Vacancies", null, t =>
                        {
                            t.HasCheckConstraint("CK_Vacancies_RequiredExperienceYears", "[RequiredExperienceYears] >= 0");
                        });
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.VacancySkill", b =>
                {
                    b.Property<int>("VacancyId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("VacancyId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("VacancySkill");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.CvMetadata", b =>
                {
                    b.HasOne("SmartRecruitment.API.Models.Entities.JobSeekerProfile", "JobSeekerProfile")
                        .WithOne("CvMetadata")
                        .HasForeignKey("SmartRecruitment.API.Models.Entities.CvMetadata", "JobSeekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeekerProfile");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Education", b =>
                {
                    b.HasOne("SmartRecruitment.API.Models.Entities.JobSeekerProfile", "JobSeekerProfile")
                        .WithMany("Educations")
                        .HasForeignKey("JobSeekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeekerProfile");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.EmployerProfile", b =>
                {
                    b.HasOne("SmartRecruitment.API.Models.Entities.User", "User")
                        .WithOne("EmployerProfile")
                        .HasForeignKey("SmartRecruitment.API.Models.Entities.EmployerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Experience", b =>
                {
                    b.HasOne("SmartRecruitment.API.Models.Entities.JobSeekerProfile", "JobSeekerProfile")
                        .WithMany("Experiences")
                        .HasForeignKey("JobSeekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeekerProfile");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.JobSeekerProfile", b =>
                {
                    b.HasOne("SmartRecruitment.API.Models.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("SmartRecruitment.API.Models.Entities.JobSeekerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRecruitment.API.Models.Entities.User", null)
                        .WithOne("JobSeekerProfile")
                        .HasForeignKey("SmartRecruitment.API.Models.Entities.JobSeekerProfile", "UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.JobSeekerSkill", b =>
                {
                    b.HasOne("SmartRecruitment.API.Models.Entities.JobSeekerProfile", "JobSeekerProfile")
                        .WithMany("JobSeekerSkills")
                        .HasForeignKey("JobSeekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRecruitment.API.Models.Entities.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobSeekerProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Notification", b =>
                {
                    b.HasOne("SmartRecruitment.API.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Vacancy", b =>
                {
                    b.HasOne("SmartRecruitment.API.Models.Entities.EmployerProfile", "EmployerProfile")
                        .WithMany("Vacancies")
                        .HasForeignKey("EmployerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployerProfile");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.VacancySkill", b =>
                {
                    b.HasOne("SmartRecruitment.API.Models.Entities.Skill", "Skill")
                        .WithMany("VacancySkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRecruitment.API.Models.Entities.Vacancy", "Vacancy")
                        .WithMany("VacancySkills")
                        .HasForeignKey("VacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Vacancy");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.EmployerProfile", b =>
                {
                    b.Navigation("Vacancies");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.JobSeekerProfile", b =>
                {
                    b.Navigation("CvMetadata");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("JobSeekerSkills");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Skill", b =>
                {
                    b.Navigation("VacancySkills");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.User", b =>
                {
                    b.Navigation("EmployerProfile");

                    b.Navigation("JobSeekerProfile");
                });

            modelBuilder.Entity("SmartRecruitment.API.Models.Entities.Vacancy", b =>
                {
                    b.Navigation("VacancySkills");
                });
#pragma warning restore 612, 618
        }
    }
}
